name = "bigbazar-web"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_APP_URL = "https://bigbazar-web.zihadlaptopasus.workers.dev"
